version: '3'
services:
  tensorflow-compiler-cpu:
    container_name: "tensorflow-compiler-cpu"
    network_mode: host
    build:
      context: .
      dockerfile: tensorflow-cpu.Dockerfile
      network: "host"
      args:
        HTTP_PROXY:
        HTTPS_PROXY:
        TF_VER:
        BRANCH_NAME:
        PYTHON_VER:
        NUMPY_VER:
        GCC_VER:
        GCC_VER_SHORT:
        BAZEL_VER:
    volumes:
      - './tensorflow:/tmp/tensorflow_pkg'
  
  tensorflow-compiler-gpu:
    container_name: "tensorflow-compiler-gpu"
    network_mode: host
    build:
      context: .
      dockerfile: tensorflow-gpu.Dockerfile
      network: "host"
      args:
        HTTP_PROXY:
        HTTPS_PROXY:
        TF_VER:
        BRANCH_NAME:
        PYTHON_VER:
        NUMPY_VER:
        GCC_VER:
        GCC_VER_SHORT:
        BAZEL_VER:
        cuDNN_VER:
        cuDNN_VER_SHORT:
        CUDA_VER:
        CUDA_DL_HTTP:
    volumes:
      - './tensorflow:/tmp/tensorflow_pkg'
    
    